export {default as LandingPage} from './LandingPage'
export {default as SignIn} from './SignIn'
export {default as Home} from './Home'
export {default as Settings} from './Settings'
export {default as Policy} from './Policy'