export {default as Feed} from './Feed'
export {default as Friends} from './Friends'
export {default as FindPeople} from './FindPeople'
export {default as SideMenu} from './SideMenu'
export {default as DesktopContainer} from './DesktopContainer'