export {default as Feed} from './Feed'
export {default as Friends} from './Friends'
export {default as FindPeople} from './FindPeople'
export {default as Friend} from './Friend'
export {default as Person} from './Person'